package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-09-08T13:02:40.120+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "LiveRequestInvokerSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface LiveRequestInvokerSoap {

    @WebMethod(operationName = "GetXMLResWithPDF", action = "http://tempuri.org/GetXMLResWithPDF")
    @RequestWrapper(localName = "GetXMLResWithPDF", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetXMLResWithPDF")
    @ResponseWrapper(localName = "GetXMLResWithPDFResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetXMLResWithPDFResponse")
    @WebResult(name = "GetXMLResWithPDFResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.LiveResponse getXMLResWithPDF(

        @WebParam(name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest,
        @WebParam(name = "strUserID", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserID,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String strPassword
    );

    @WebMethod(operationName = "PostRequest", action = "http://tempuri.org/PostRequest")
    @RequestWrapper(localName = "PostRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostRequest")
    @ResponseWrapper(localName = "PostRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostRequestResponse")
    @WebResult(name = "PostRequestResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String postRequest(

        @WebParam(name = "strRequest", targetNamespace = "http://tempuri.org/")
        java.lang.String strRequest,
        @WebParam(name = "strUserID", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserID,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String strPassword
    );

    @WebMethod(operationName = "ResponseByTicketID", action = "http://tempuri.org/ResponseByTicketID")
    @RequestWrapper(localName = "ResponseByTicketID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResponseByTicketID")
    @ResponseWrapper(localName = "ResponseByTicketIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ResponseByTicketIDResponse")
    @WebResult(name = "ResponseByTicketIDResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.LiveResponse responseByTicketID(

        @WebParam(name = "strTicketId", targetNamespace = "http://tempuri.org/")
        java.lang.String strTicketId,
        @WebParam(name = "subjectType", targetNamespace = "http://tempuri.org/")
        int subjectType,
        @WebParam(name = "strUserID", targetNamespace = "http://tempuri.org/")
        java.lang.String strUserID,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String strPassword
    );
}
