package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-09-08T13:02:40.162+02:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "LiveRequestInvoker",
                  wsdlLocation = "file:/C:/Users/MagedMamdouh/Documents/NetBeansProjects/iscoreCXF/src/main/resources/wsdl/LiveRequestInvoker.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class LiveRequestInvoker extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "LiveRequestInvoker");
    public final static QName LiveRequestInvokerSoap12 = new QName("http://tempuri.org/", "LiveRequestInvokerSoap12");
    public final static QName LiveRequestInvokerSoap = new QName("http://tempuri.org/", "LiveRequestInvokerSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/MagedMamdouh/Documents/NetBeansProjects/iscoreCXF/src/main/resources/wsdl/LiveRequestInvoker.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LiveRequestInvoker.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/MagedMamdouh/Documents/NetBeansProjects/iscoreCXF/src/main/resources/wsdl/LiveRequestInvoker.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LiveRequestInvoker(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LiveRequestInvoker(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LiveRequestInvoker() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LiveRequestInvoker(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LiveRequestInvoker(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LiveRequestInvoker(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LiveRequestInvokerSoap
     */
    @WebEndpoint(name = "LiveRequestInvokerSoap12")
    public LiveRequestInvokerSoap getLiveRequestInvokerSoap12() {
        return super.getPort(LiveRequestInvokerSoap12, LiveRequestInvokerSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LiveRequestInvokerSoap
     */
    @WebEndpoint(name = "LiveRequestInvokerSoap12")
    public LiveRequestInvokerSoap getLiveRequestInvokerSoap12(WebServiceFeature... features) {
        return super.getPort(LiveRequestInvokerSoap12, LiveRequestInvokerSoap.class, features);
    }


    /**
     *
     * @return
     *     returns LiveRequestInvokerSoap
     */
    @WebEndpoint(name = "LiveRequestInvokerSoap")
    public LiveRequestInvokerSoap getLiveRequestInvokerSoap() {
        return super.getPort(LiveRequestInvokerSoap, LiveRequestInvokerSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LiveRequestInvokerSoap
     */
    @WebEndpoint(name = "LiveRequestInvokerSoap")
    public LiveRequestInvokerSoap getLiveRequestInvokerSoap(WebServiceFeature... features) {
        return super.getPort(LiveRequestInvokerSoap, LiveRequestInvokerSoap.class, features);
    }

}
